### ISSUE TITLE
Second twitter instance is crashing on OS X

### ISSUE THREAD

**Issue by n2o** [Wegi/trickle#6]
This happens on my machine (OS X 10.9.4) and not on the developer's machine:
1. Create one box and connect to twitter
2. Create another box and again try to connect to twitter
3. Error!

_Cannot read property 'id' of undefined_

**Comment by n2o** [comment]
![Error](https://cloud.githubusercontent.com/assets/1507474/4182941/5ce2d2d6-3736-11e4-8048-d66766be92da.png)

**Comment by Wegi** [comment]
fixed
